# Generated by Django 3.0.3 on 2020-07-11 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 7, 11, 13, 11, 15, 676795, tzinfo=utc)),
        ),
    ]
