# Generated by Django 3.0.3 on 2020-07-11 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200711_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 7, 11, 13, 13, 16, 119543, tzinfo=utc)),
        ),
    ]
