# Generated by Django 3.0.3 on 2020-07-11 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200711_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='date',
        ),
        migrations.AlterField(
            model_name='mylist',
            name='category',
            field=models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='list.Category'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
